### ISSUE TITLE
Unconfigured table <tablename>

### ISSUE THREAD

**Issue by satheshramasamy** [loopbackio/loopback-connector-cassandra#88]
Im working with loopback 4 and cassandra,

Model, controller, repository and datasource are created successfully, Also loopback 4 server started without any error.
At the time of post or get a method form model im getting error msg "unconfigured Table tablename". Table already created in database manually.

`
Unhandled error in GET /testmodels: 500 ResponseError: unconfigured table Testmodel
    at FrameReader.readError (D:\version2\lb4\explore\node_modules\cassandra-driver\lib\readers.js:326:15)
    at Parser.parseBody (D:\version2\lb4\explore\node_modules\cassandra-driver\lib\streams.js:194:66)
    at Parser._transform (D:\version2\lb4\explore\node_modules\cassandra-driver\lib\streams.js:137:10)
    at Parser.Transform._read (_stream_transform.js:190:10)
    at Parser.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at Parser.Writable.write (_stream_writable.js:299:11)
    at Protocol.ondata (_stream_readable.js:693:20)
    at Protocol.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Protocol.Readable.push (_stream_readable.js:224:10)
    at Protocol.Transform.push (_stream_transform.js:151:32)
    at Protocol.readItems (D:\version2\lb4\explore\node_modules\cassandra-driver\lib\streams.js:109:10)
    at Protocol._transform (D:\version2\lb4\explore\node_modules\cassandra-driver\lib\streams.js:32:10)`

**Comment by dhmlau** [comment]
@jannyHou, could you please take a look? Thanks.
